"""Test classes for the models module."""

from dataclasses import dataclass, field
from enum import Enum

from src.models.problem import Problem, ProblemMetadata, ProblemCategory
from src.models.solution import SolutionTrace, SolutionStep, StepType, ExtractedCalculation


class ConfidenceLevel(Enum):
    """Levels of confidence in a verification result."""
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    UNKNOWN = "UNKNOWN"


@dataclass(frozen=True)
class VerificationReport:
    """Report generated by the verification pipeline."""
    passed_checks: int = 0
    failed_checks: int = 0
    confidence: ConfidenceLevel = ConfidenceLevel.UNKNOWN

    @property
    def pass_rate(self) -> float:
        """Calculate the pass rate of checks."""
        total = self.passed_checks + self.failed_checks
        if total == 0:
            return 0.0
        return self.passed_checks / total

    @property
    def has_failures(self) -> bool:
        """Check if any checks failed."""
        return self.failed_checks > 0


@dataclass(frozen=True)
class Critique:
    """A critique of a solution."""
    fatal_flaws: list[str] = field(default_factory=list)
    critic_agreements: int = 0
    critic_disagreements: int = 0

    @property
    def has_fatal_flaws(self) -> bool:
        """Check if the critique found any fatal flaws."""
        return len(self.fatal_flaws) > 0

    @property
    def critics_agree(self) -> bool:
        """Check if critics agree (more agreements than disagreements)."""
        return self.critic_agreements > self.critic_disagreements


class SchemaValidation:
    """Schema validation logic."""
    def __init__(self, problem_count: int = 0):
        self.problem_count = problem_count

    @property
    def is_validated_logic(self) -> bool:
        """Check if logic is validated based on sufficient problem count."""
        return self.problem_count >= 10
